# Generated by Django 4.1.1 on 2023-06-06 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_country', models.CharField(blank=True, max_length=50, null=True)),
                ('company_state', models.CharField(blank=True, max_length=50, null=True)),
                ('company_zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('company_location', models.CharField(blank=True, max_length=50, null=True)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('user_login', models.CharField(blank=True, max_length=50, null=True)),
                ('company_website', models.CharField(blank=True, max_length=50, null=True)),
                ('company_info', models.CharField(blank=True, max_length=50, null=True)),
                ('is_public', models.CharField(blank=True, max_length=50, null=True)),
                ('company_slogan', models.CharField(blank=True, max_length=50, null=True)),
                ('group_image', models.CharField(blank=True, max_length=50, null=True)),
                ('remote_ready', models.CharField(blank=True, max_length=50, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=50, null=True)),
                ('field_8', models.CharField(blank=True, max_length=50, null=True)),
                ('field_5', models.CharField(blank=True, max_length=50, null=True)),
                ('field_6', models.CharField(blank=True, max_length=50, null=True)),
                ('field_7', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('job_country', models.CharField(blank=True, max_length=50, null=True)),
                ('job_state', models.CharField(blank=True, max_length=50, null=True)),
                ('job_zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('job_city', models.CharField(blank=True, max_length=50, null=True)),
                ('job_address', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('job_created_at', models.DateField(default=django.utils.timezone.now)),
                ('job_expires_at', models.DateField(default=jobs.models.in_three_days)),
                ('company_website', models.URLField()),
                ('job_description', models.TextField(unique=True)),
                ('wpjobboard_am_data', models.URLField()),
                ('company_url', models.URLField()),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_logo', models.ImageField(upload_to='')),
                ('company_country', models.CharField(blank=True, max_length=50, null=True)),
                ('company_state', models.CharField(blank=True, max_length=50, null=True)),
                ('company_zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('company_location', models.CharField(blank=True, max_length=50, null=True)),
                ('company_info', models.CharField(blank=True, max_length=50, null=True)),
                ('is_public', models.CharField(blank=True, max_length=50, null=True)),
                ('company_slogan', models.CharField(blank=True, max_length=50, null=True)),
                ('remote_ready', models.CharField(blank=True, max_length=50, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('job_description_format', models.CharField(default='html', max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.company', verbose_name='company')),
            ],
        ),
    ]
