# Generated by Django 4.1.1 on 2023-06-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='wpjobboard_am_data',
            field=models.URLField(unique=True),
        ),
    ]
