# Generated by Django 4.1.1 on 2023-06-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_wpjobboard_am_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
