# Generated by Django 4.1.1 on 2023-06-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobs_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_created_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
