# Generated by Django 4.1.1 on 2023-06-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobs_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
