# Generated by Django 4.1.1 on 2023-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobs_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='wpjobboard_am_data',
            field=models.URLField(),
        ),
    ]
